#!/bin/sh

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

pattern="^(fix|feat|build|chore|ci|docs|style|refactor|perf|test)(\([\w-]+\))?!?: .+"

if ! echo "$commit_msg" | grep -qE "$pattern"; then
  echo "❌ Incorrect commit message format!"
  echo "Example: feat(login): add user login feature"
  exit 1
fi
